// Errors
export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

// Auth
export const SET_CURRENT_USER = "SET_CURRENT_USER";

// Profile
export const GET_USER_PROFILE = "GET_USER_PROFILE";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

//Books
export const GET_ALL_BOOKS = "GET_ALL_BOOKS";
export const GET_ALL_BOOK_SERIES = "GET_ALL_BOOK_SERIES"
export const GET_BOOKS_LOADING = "GET_BOOKS_LOADING";
export const GET_BOOK_SERIES_LOADING = "GET_BOOK_SERIES_LOADING";
export const CLEAR_CURRENT_BOOKS = "CLEAR_CURRENT_BOOKS";

// Inventory
export const INVENTORY_LOADING = "INVENTORY_LOADING";
export const GET_ALL_INVENTORY = "GET_ALL_INVENTORY";
export const CLEAR_CURRENT_INVENTORY = "CLEAR_CURRENT_INVENTORY";

// Sales
export const GET_ALL_SALES = "GET_ALL_SALES";
export const SALES_LOADING = "SALES_LOADING";
export const CLEAR_CURRENT_SALES = "CLEAR_CURRENT_SALES";

// Production Costs
export const GET_ALL_PRODUCTION_COSTS = "GET_ALL_PRODUCTION_COSTS";
export const PRODUCTION_COSTS_LOADING = "PRODUCTION_COSTS_LOADING";
export const CLEAR_CURRENT_PRODUCTION_COSTS = "CLEAR_CURRENT_PRODUCTION_COSTS";

// Production Costs
export const GET_ALL_PERIODICAL_COSTS = "GET_ALL_PERIODICAL_COSTS";
export const PERIODICAL_COSTS_LOADING = "PERIODICAL_COSTS_LOADING";
export const CLEAR_CURRENT_PERIODICAL_COSTS = "CLEAR_CURRENT_PERIODICAL_COSTS";
